### PR TITLE
Support for Python 3

### PR DESCRIPTION
**Pull request by george-hopkins**
As more and more projects are based on Python 3, this PR hopefully makes all current modules compatible with Python 3.

All tests pass for 2.7, 3.3 and 3.5: https://travis-ci.org/george-hopkins/pyutil/builds/189805907

### CODE REVIEW

**Comment by george-hopkins** [comment]
Small update: I added an update of versioneer to get correct version tags.

CI: https://travis-ci.org/george-hopkins/pyutil/builds/189832255

**Comment by sbellem** [comment]
May we simply know what's the status on this PR? Are there plans to take care of it and merge it soon?

**Comment by zookozcash** [comment]
I'm sorry, I'm not maintaining pyutil anymore. We need someone else to maintain it!

**Comment by sbellem** [comment]
Thanks for your quick reply! (_Sorry for my late reply!_) I was asking because of the related PR on zfec (https://github.com/tahoe-lafs/zfec/pull/4).

Just in case that it is not too much trouble for you, you can perhaps shine some light on the following question asked by @warner in https://github.com/tahoe-lafs/zfec/pull/4#issuecomment-315575007:

> What do we need pyutil for anyways? (I vaguely remember talking with zooko a long while back about maybe splitting the CLI utilities out of zfec and into a separate package, because I seem to remember that pyutil was only needed for the CLI tools).

Thanks!

**Comment by zooko** [comment]
Best to grep the Tahoe source code to answer that, or ask someone who is a
current maintainer of it.

**Comment by sbellem** [comment]
> Best to grep the Tahoe source code to answer that, or ask someone who is a current maintainer of it.

Ok, cool, thanks!

**Comment by tpltnt** [comment]
@george-hopkins can you do the same PR over [here](https://github.com/tpltnt/pyutil)? I took over maintainership and would like to integrate your work.

**Comment by george-hopkins** [comment]
@tpltnt Sure, I will do a rebase of my patch as soon as possible. Btw, would you mind enabling issues on your fork? That would enable us to discuss the integration in a separate thread.

**Comment by tpltnt** [comment]
@george-hopkins cool, thank you

**Comment by tpltnt** [comment]
Python 3 support landed in my branch and in the module on pypi.

**Pull request closed without merging**
